version: "3.9"

services:
  api:
    build: .
    command: uvicorn apps.api_fastapi.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data/storage:/app/data/storage
    depends_on:
      - embeddings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  ui:
    build: .
    command: streamlit run apps/ui_streamlit/Home.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./data/storage:/app/data/storage

  embeddings:
    image: python:3.11-slim
    command: ["sleep", "infinity"]
    volumes:
      - ./data/storage:/app/data/storage

volumes:
  data:
